'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/53/CMP_FILE?referer=www.drivemad.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #368bd6 !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #368bd6 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=3;function splitLang(lang){if(lang.includes('pt')&&lang.length>2){return lang.split('-')[0]+'-'+lang.split('-')[1].toLowerCase();}
return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','uk','zh','id','ko','ja','hi','vi','th','ms'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"siteUuid":"22efbcf7-3ac7-45fb-887b-2f8d73f675da","themeUuid":"7ef284a7-95ee-46c5-ab1d-53a80b077e2c","inmobiAccountId":"gzcxYE0cpD4Ds","privacyMode":["GDPR"],"includeVendorsDisclosedSegment":false,"cmpVersion":"53","hashCode":"1Sjd9O/AlNLY94TNhhi7fQ","publisherCountryCode":"SE","publisherName":"Drive Mad","vendorPurposeIds":[2,4,6,7,9,10,1,3,5,8,11],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[2,7,8,10,9,11],"vendorSpecialFeaturesIds":[1,2],"vendorSpecialPurposesIds":[1,2,3],"googleEnabled":false,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"always","softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"uiLayout":"popup","vendorListUpdateFreq":30,"publisherPurposeIds":[],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[1,42],"lang_":"en","gvlVersion":3,"totalVendors":915,"legitimateInterestOptIn":true,"features":{"visitEvents":true},"translationUrls":{"common":"https://cmp.inmobi.com/tcfv2/translations/${language}.json","theme":"https://cmp.inmobi.com/custom-translations/inmobi/7ef284a7-95ee-46c5-ab1d-53a80b077e2c/${language}.json","all":"https://cmp.inmobi.com/consolidated-translations/inmobi/7ef284a7-95ee-46c5-ab1d-53a80b077e2c/${language}.json"},"gdprEnabledInUS":false},"premiumUiLabels":{},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{},"theme":{},"nonIabVendorsInfo":{"nonIabVendorList":[{"vendorId":2,"pCode":"gzcxYE0cpD4Ds","name":"Poki B.V.","description":null,"privacyPolicyUrl":"https://poki.com/en/c/global-privacy-statement","nonIabPurposeConsentIds":[1],"nonIabPurposeLegitimateInterestIds":[],"active":null,"gvlVersion":3}]}});})();